### ISSUE TITLE
6. Building the game scene - Penguin Launcher model 1 formatting error

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#16]
<img width="661" alt="screen shot 2017-06-09 at 5 42 54 pm" src="https://user-images.githubusercontent.com/14242863/26998617-1e9e2c82-4d3b-11e7-9476-efbeba0d3886.png">

Some formatting weirdness in the tutorial.

**Comment by dionlarson** [comment]
Fixed
