### ISSUE TITLE
7. Creating your first level - Weird Formatting

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#18]
<img width="854" alt="screen shot 2017-06-09 at 6 07 55 pm" src="https://user-images.githubusercontent.com/14242863/26998818-9e3aea04-4d3e-11e7-85bc-89949c8bd7fe.png">

1. Looks like that quote was supposed to be an action, based on the "[Action]" tag there in the text. 
2. Looks like the line "The questionmark (?) after the type declares cameraTarget as an optional." should be "The question mark (?) after the type declares cameraTarget as an optional." and should be moved under the action that adds the cameraTarget optional.

**Comment by dionlarson** [comment]
Fixed
