### ISSUE TITLE
7. Creating your first level - Typo/Grammatical fix

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#19]
"This function check if if cameraTarge is nil, it's an optional remember!" -> "This function checks if cameraTarget is nil. It's an optional remember!" or, better yet "This function checks if cameraTarget is nil. Remember to check for nil on optionals that may not contain a value or you can end up crashing your game!"

**Comment by dionlarson** [comment]
Fixed
