### ISSUE TITLE
5. Adding the main menu

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#2]
In Launching the Main Scene - it instructs the students to "Replace with: if let scene = MainMenu(fileNamed: "MainMenu") {" - the only problem here is that just above the tutorial instructs them to name the .sks "MainScene" instead of "MainMenu"

**Comment by zontan** [comment]
In Load the Game Scene - "Make to add the function below inside the MainMenu class."

**Comment by dionlarson** [comment]
Reverted original instructions to be `MainMenu`
