### ISSUE TITLE
7. Creating your first level - touchesBegan issue

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#20]
This step asks you to add the line "cameraTarget = penguin" to the "touchesEnded" method. However, in the initial GameScene code, we do not add that method. Students should be able to figure this out, but just in case...

Also, that line asks you to use "penguin" which, since we haven't used this method yet in the tutorial, is not defined inside the scope of that method. 

If we add "let penguin = Penguin()" to the "touchesEnd" method, however, you aren't looking at the penguin spawned in touchesBegan. 

If we just add "cameraTarget = penguin" to the "touchesBegan" method, the code then works fine.

**Comment by dionlarson** [comment]
Fixed
