### ISSUE TITLE
9. Catapult physics - Typo

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#22]
"This will release the joint holding the catapult arm and touchNode, allowing the forced stored in the cantileverNode spring joint to exert its force." -> "This will release the joint holding the catapult arm and touchNode, allowing the force stored in the cantileverNode spring joint to exert its force."

**Comment by dionlarson** [comment]
Fixed
