### ISSUE TITLE
11. Working with contacts and collisions - Typo

### ISSUE THREAD

**Issue by Hassurunous** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#23]
Add the dieSeal method to your GameScene class:
func removeSeal(node: SKNode) {
   /* Seal death*/

   /* Create our hero death action */
   let sealDeath = SKAction.run({
        /* Remove seal node from scene */
        node.removeFromParent()
    })
    self.run(sealDeath)
}

Message says "dieSeal method" but the actual method is called "removeSeal".

**Comment by dionlarson** [comment]
Fixed
