### ISSUE TITLE
7. Creating your first level

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#5]
In the subsection: Camera Target

We are asked to put code in the "touchesEnded()" function but we were never asked to override this function prior to this. This is not an issue as anyone reading along and understanding what they're reading would know to add the function override themselves but the code snippet below that doesn't actually do anything yet and seems broken or out of place. I think this is supposed to say "touchesBegan()."

<img width="779" alt="screen shot 2017-06-08 at 6 35 39 am" src="https://user-images.githubusercontent.com/13054451/26924719-ec1fa348-4c14-11e7-96c4-ab12f052cf86.png">

**Comment by dionlarson** [comment]
Fixed
