### ISSUE TITLE
9. Catapult physics

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Peeved-Penguins-SpriteKit-Swift3-V2#9]
There's a lot of little formatting errors on this page:

-In Getting the physics bodies ready, the code at the bottom is not in code blocks.'

-In Creating a physics body and joint, the action panel is an info panel, and some of the code is not in a code block.

-Towards the bottom of that same section (when adding the cantilever node), another action has a visible [action] inside it, and a line that isn't code blocked.

-In Adding the touch node, the last code snippet is not code blocked.

**Comment by dionlarson** [comment]
Fixed
